[package]
name = "Blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
rdkafka = "0.36.2"
sha2 = "0.11.0-pre.4"
hex = "0.4.3"